export const ERROR_CODES = {
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_BLOCKED: 'AUTH_ACCOUNT_BLOCKED',

  SESSION_INVALID_REFRESH_TOKEN: 'SESSION_INVALID_REFRESH_TOKEN',

  USER_EMAIL_ALREADY_EXISTS: 'USER_EMAIL_ALREADY_EXISTS',
  DEBT_INVALID_AMOUNT: 'DEBT_INVALID_AMOUNT',
  DEBT_SAME_DEBTOR_AND_CREDITOR: 'DEBT_SAME_DEBTOR_AND_CREDITOR',
  DEBT_ALREADY_PAID: 'DEBT_ALREADY_PAID',
  DEBT_ACTIVE_LIMIT_EXCEEDED: 'DEBT_ACTIVE_LIMIT_EXCEEDED',
  DEBTOR_NOT_FOUND: 'DEBTOR_NOT_FOUND',
  CREDITOR_NOT_FOUND: 'CREDITOR_NOT_FOUND',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
