import { HttpStatus } from '@nestjs/common';

import { ERROR_CODES, ErrorCode } from './error-codes.constant';

/**
 * Mapeo de códigos de error a HTTP status
 */
export const ERROR_HTTP_STATUS: Record<ErrorCode, HttpStatus> = {
  // Genéricos
  [ERROR_CODES.INTERNAL_ERROR]: HttpStatus.INTERNAL_SERVER_ERROR,
  [ERROR_CODES.VALIDATION_ERROR]: HttpStatus.BAD_REQUEST,

  // Auth
  [ERROR_CODES.AUTH_INVALID_CREDENTIALS]: HttpStatus.UNAUTHORIZED,
  [ERROR_CODES.AUTH_ACCOUNT_BLOCKED]: HttpStatus.LOCKED,
  [ERROR_CODES.UNAUTHORIZED]: HttpStatus.UNAUTHORIZED,
  [ERROR_CODES.SESSION_EXPIRED]: HttpStatus.UNAUTHORIZED,

  // Session
  [ERROR_CODES.SESSION_INVALID_REFRESH_TOKEN]: HttpStatus.UNAUTHORIZED,

  // User
  [ERROR_CODES.USER_EMAIL_ALREADY_EXISTS]: HttpStatus.CONFLICT,

  // Debt
  [ERROR_CODES.DEBT_INVALID_AMOUNT]: HttpStatus.BAD_REQUEST,
  [ERROR_CODES.DEBT_SAME_DEBTOR_AND_CREDITOR]: HttpStatus.BAD_REQUEST,
  [ERROR_CODES.DEBT_ALREADY_PAID]: HttpStatus.CONFLICT,
  [ERROR_CODES.DEBT_ACTIVE_LIMIT_EXCEEDED]: HttpStatus.CONFLICT,
  [ERROR_CODES.DEBTOR_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [ERROR_CODES.CREDITOR_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [ERROR_CODES.DEBT_NOT_FOUND]: HttpStatus.NOT_FOUND,
};
